### ISSUE TITLE
Problem on Pi Zero W

### ISSUE THREAD

**Issue by SP3WRO** [projecthorus/horusdemodlib#187]
Installed according to your instructions. Doesn't work. Any tips?
New Pi Zero W, green rtl-sdr, raspberry pi os 2023-10-10
```
czysty@pizero:~ $ sudo horusdemodlib/./start_rtlsdr.sh
Found horus_demod.
Found bc.
Entering venv.
Using SDR Centre Frequency: 434194000 Hz.
Using FSK estimation range: 1000 - 11000 Hz
Using AGC.
Setting estimator limits to 1000 to 11000 Hz.
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to automatic.
Tuner error set to 1 ppm.
Tuned to 434578000 Hz.
Oversampling input by: 32x.
Oversampling output by: 1x.
Buffer size: 5.33ms
Allocating 15 zero-copy buffers
Sampling at 1536000 S/s.
Output at 48000 Hz.
Traceback (most recent call last):
  File "/home/czysty/horusdemodlib/venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/czysty/horusdemodlib/venv/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/czysty/horusdemodlib/venv/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/czysty/horusdemodlib/venv/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/czysty/horusdemodlib/venv/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/czysty/horusdemodlib/venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/home/czysty/horusdemodlib/venv/bin/python3"
  * The NumPy version is: "1.26.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/czysty/horusdemodlib/horusdemodlib/uploader.py", line 23, in <module>
    from .demodstats import FSKDemodStats
  File "/home/czysty/horusdemodlib/horusdemodlib/demodstats.py", line 17, in <module>
    import numpy as np
  File "/home/czysty/horusdemodlib/venv/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
Signal caught, exiting!

User cancel, exiting...

```

**Comment by darksidelemm** [comment]
The link in the error message has solutions for raspberry pi:
https://numpy.org/devdocs/user/troubleshooting-importerror.html#raspberry-pi

Try installing the package they mention, and then try again.
